version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_WEATHER_WEBSOCKET: ${NEXT_PUBLIC_WEATHER_WEBSOCKET}
        NEXT_PUBLIC_SEISMIC_WEBSOCKET: ${NEXT_PUBLIC_SEISMIC_WEBSOCKET}
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WEATHER_WEBSOCKET=${NEXT_PUBLIC_WEATHER_WEBSOCKET}
      - NEXT_PUBLIC_SEISMIC_WEBSOCKET=${NEXT_PUBLIC_SEISMIC_WEBSOCKET}
      - NEXT_PUBLIC_FILE_API_ENDPOINT=${NEXT_PUBLIC_FILE_API_ENDPOINT}
      - NEXT_PUBLIC_KEYCLOAK_URL=${NEXT_PUBLIC_KEYCLOAK_URL}
      - NEXT_PUBLIC_KEYCLOAK_REALM=${NEXT_PUBLIC_KEYCLOAK_REALM}
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=${NEXT_PUBLIC_KEYCLOAK_CLIENT_ID}
    container_name: data-station
    ports:
      - "4004:4004"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.122

networks:
  nginx-manager_customnetwork:
    external: true
