version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-station
    ports:
      - "4001:4001"
    env_file:
      - stack.env
    restart: unless-stopped
