version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    # pull_policy: build
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: data-station
    ports:
      - "4003:4003"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      data-station-network:
        ipv4_address: 172.20.14.95

networks:
  data-station-network:
    external: true
