version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: data-station
    ports:
      - "4004:4004"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.122

networks:
  nginx-manager_customnetwork:
    external: true
