version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-station
    ports:
      - "4002:4002"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      data-station-network:
        ipv4_address: 172.20.14.95

networks:
  data-station-network:
    external: true
